-- MySQL Script generated by MySQL Workbench
-- Wed Mar 13 15:19:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Flight_Scanner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Flight_Scanner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Flight_Scanner` DEFAULT CHARACTER SET utf8 ;
USE `Flight_Scanner` ;

-- -----------------------------------------------------
-- Table `Flight_Scanner`.`Airports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airports` (
  `Airport_code_id` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Address` VARCHAR(100) NULL,
  `State` VARCHAR(25) NULL,
  `City` VARCHAR(50) NULL,
  UNIQUE INDEX `Airport_code_id_UNIQUE` (`Airport_code_id` ASC) VISIBLE,
  PRIMARY KEY (`Airport_code_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Flight_Scanner`.`Airplanes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Airplanes` (
  `Airplane_type_id` INT NOT NULL,
  `Airline` VARCHAR(50) NULL,
  `no_main_seats` INT NULL,
  `M_available` INT NULL,
  `M_total` INT NULL,
  `no_business_seats` INT NULL,
  `B_available` INT NULL,
  `B_total` INT NULL,
  `no_first_seats` INT NULL,
  `F_available` INT NULL,
  `F_total` INT NULL,
  PRIMARY KEY (`Airplane_type_id`),
  UNIQUE INDEX `Airplane_type_id_UNIQUE` (`Airplane_type_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Flight_Scanner`.`Air routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Air_Routes` (
  `Route_ID` INT NOT NULL,
  `Distance` INT NULL,
  `Time` DATE NULL,
  `Cost_of_flight` INT NULL,
  `Airports` VARCHAR(50) NULL,
  PRIMARY KEY (`Route_ID`),
  UNIQUE INDEX `Route_ID_UNIQUE` (`Route_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Flight_Scanner`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Schedule` (
  `Route_ID` INT NOT NULL,
  `Airplane_type_id` INT NULL,
  `Airport_code_id` INT NULL,
  UNIQUE INDEX `Route_ID_UNIQUE` (`Route_ID` ASC) VISIBLE,
  UNIQUE INDEX `Airplane_type_id_UNIQUE` (`Airplane_type_id` ASC) VISIBLE,
  UNIQUE INDEX `Airport_code_id_UNIQUE` (`Airport_code_id` ASC) VISIBLE,
  CONSTRAINT `Route_ID`
    FOREIGN KEY (`Route_ID`)
    REFERENCES `Flight_Scanner`.`Air routes` (`Route_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Airplane_type_id`
    FOREIGN KEY (`Airplane_type_id`)
    REFERENCES `Flight_Scanner`.`Airplanes` (`Airplane_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Airport_code_id`
    FOREIGN KEY (`Airport_code_id`)
    REFERENCES `Flight_Scanner`.`Airports` (`Airport_code_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- inserting in practice values and practice queries
-- -----------------------------------------------------
INSERT INTO Air_Routes(Route_ID, Distance, Time, Cost_of_flight, Airports) 
  values (1, 2, '2023-01-01', 35.00, 'DSM');

SELECT * FROM Air_Routes
